import turtle
Jammy = turtle.Turtle()
my_screen=turtle.Screen()
my_screen.bgcolor('pink')
Jammy.shape("turtle")
Jammy.circle(100)
Jammy.color("red")
Jammy.circle(90)
Jammy.color("blue")
Jammy.circle(80)
Jammy.color("green")
Jammy.circle(70)
Jammy.color("purple")
Jammy.circle(60)
Jammy.color("yellow")
Jammy.circle(50)
Jammy.color("orange")
Jammy.circle(40)
Jammy.right(90)
Jammy.forward(200)
Jammy.left(90)
Jammy.forward(2)
Jammy.left(90)
Jammy.forward(200)

my_screen.exitonclick()
