from turtle import Turtle,Screen
screen=Screen()
pet=Turtle()
pet.shape("arrow")
pet.color('blue')
pet.pensize(10)
tup=(0.2,0.3,0.5)
pet.pencolor(tup)
pet.pendown()
pet.forward(200)
pet.left(90)
pet.forward(200)
pet.left(90)
pet.forward(200)
pet.left(90)
pet.forward(200)
pet.left(90)
pet.reset()

screen.exitonclick()